volumes:
    postgres-data:
        external: true

services:
    fastapi:
        environment:
            CORS_HOST: http://localhost:5173
            DATABASE_URL: postgresql://wtv:wtv@postgres/wtv
            SIGNING_KEY: yv7pzYT-Q-ZlUlvcuITjNU4xsxEV63Dnx
            WAIT_BEFORE: 5
            WAIT_TIMEOUT: 60
        build:
            context: api
            dockerfile: Dockerfile.dev
        ports:
            - 8000:8000
        user: "1000:1000" # on macOS and Linux, replace this with your real user id and group id
        volumes:
            - ./api:/app

    ghi:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        user: "1000:1000" # on macOS and Linux, replace this with your real user id and group id
        volumes:
            - ./ghi:/app
        environment:
            VITE_API_HOST: http://localhost:8000
        ports:
            - "5173:5173"

    postgres:
        image: postgres:14.5-bullseye
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: wtv
            POSTGRES_USER: wtv
            POSTGRES_DB: wtv
        ports:
            - 15432:5432
